# Generated by Django 3.1.3 on 2020-11-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201126_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_field',
            new_name='user',
        ),
    ]
