# Generated by Django 3.1.3 on 2020-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='name', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
