# Generated by Django 3.1.3 on 2020-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmp3',
            name='url',
            field=models.TextField(default='http:'),
        ),
    ]
