# Generated by Django 3.1.3 on 2020-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_app', '0002_newmp3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmp3',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
